sudo: required
language: rust
dist: xenial

rust:
  - 1.31.0

env:
  global:
    - RUST_BACKTRACE=1

cache: 
  - cargo
  - pip

before_install:
  - sudo apt-get -y install python3.5-pip python3.5-dev libopenmpi-dev
  - sudo pip3 install -U --upgrade pip
  - sudo pip3 install -U --only-binary=numpy pillow gym==0.10.5 atari_py pillow tensorflow opencv-python joblib mpi4py six

before_script:
  - rustup component add rustfmt-preview

script: ./check.sh
